name: doxygen documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  doxygen:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: iotivity-lite
      
       
      - name: build_documentation
        run: |
          sudo apt-get update -y
          sudo apt-get install doxygen
          doxygen --version
          cd ${{ github.workspace }}/iotivity-lite/tools
          ./build_doc.sh
          
